# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'k_space.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(697, 392)
        self.groupBox_8 = QtWidgets.QGroupBox(Form)
        self.groupBox_8.setGeometry(QtCore.QRect(330, 80, 301, 271))
        self.groupBox_8.setObjectName("groupBox_8")
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 80, 301, 271))
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 651, 71))
        self.groupBox.setObjectName("groupBox")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 10, 121, 51))
        self.groupBox_5.setObjectName("groupBox_5")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_3.setGeometry(QtCore.QRect(70, 20, 41, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 20, 51, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_6.setGeometry(QtCore.QRect(140, 10, 101, 51))
        self.groupBox_6.setObjectName("groupBox_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 20, 41, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_7.setGeometry(QtCore.QRect(60, 20, 31, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(250, 10, 291, 51))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 20, 61, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setGeometry(QtCore.QRect(80, 20, 61, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_5.setGeometry(QtCore.QRect(150, 20, 61, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_8.setGeometry(QtCore.QRect(220, 20, 61, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(630, 80, 41, 271))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalSlider = QtWidgets.QSlider(self.groupBox_3)
        self.verticalSlider.setGeometry(QtCore.QRect(10, 50, 20, 211))
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_8.setGeometry(QtCore.QRect(0, 20, 41, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_8.setTitle(_translate("Form", "k space processed"))
        self.groupBox_4.setTitle(_translate("Form", "k space origin"))
        self.groupBox.setTitle(_translate("Form", "dataprocess"))
        self.groupBox_5.setTitle(_translate("Form", "Symmetry box"))
        self.pushButton_6.setToolTip(_translate("Form", "进行对称化操作"))
        self.pushButton_6.setText(_translate("Form", "Do it"))
        self.groupBox_6.setTitle(_translate("Form", "Log box"))
        self.pushButton_7.setToolTip(_translate("Form", "进行Log操作"))
        self.pushButton_7.setText(_translate("Form", "Do it"))
        self.groupBox_2.setTitle(_translate("Form", "OpenCV_Toolbox"))
        self.pushButton_3.setToolTip(_translate("Form", "open_cv的功能,尚未开发"))
        self.pushButton_3.setText(_translate("Form", "消除尖峰"))
        self.pushButton_4.setToolTip(_translate("Form", "open_cv的功能,尚未开发"))
        self.pushButton_4.setText(_translate("Form", "过滤"))
        self.pushButton_5.setToolTip(_translate("Form", "open_cv的功能,尚未开发"))
        self.pushButton_5.setText(_translate("Form", "LineCut"))
        self.pushButton_8.setToolTip(_translate("Form", "open_cv的功能,尚未开发"))
        self.pushButton_8.setText(_translate("Form", "待定"))
        self.groupBox_3.setTitle(_translate("Form", "Bias"))

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_Form()
    ui.setupUi(mainWindow)
    mainWindow.show()
    app.exec_()