# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qpi.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(677, 388)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 30, 651, 51))
        self.groupBox.setObjectName("groupBox")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(10, 20, 51, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(80, 20, 41, 16))
        self.label_5.setObjectName("label_5")
        self.horizontalSlider_5 = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider_5.setGeometry(QtCore.QRect(120, 20, 121, 16))
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setObjectName("horizontalSlider_5")
        self.horizontalSlider_6 = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider_6.setGeometry(QtCore.QRect(290, 20, 121, 16))
        self.horizontalSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_6.setObjectName("horizontalSlider_6")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(250, 20, 41, 16))
        self.label_6.setObjectName("label_6")
        self.groupBox_8 = QtWidgets.QGroupBox(Form)
        self.groupBox_8.setGeometry(QtCore.QRect(320, 90, 301, 271))
        self.groupBox_8.setObjectName("groupBox_8")
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 90, 301, 271))
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(620, 90, 41, 271))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalSlider = QtWidgets.QSlider(self.groupBox_3)
        self.verticalSlider.setGeometry(QtCore.QRect(10, 30, 20, 231))
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(10, 10, 21, 16))
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "E-q关系拟合"))
        self.pushButton.setText(_translate("Form", "拟合"))
        self.label_5.setText(_translate("Form", "参数A:"))
        self.label_6.setText(_translate("Form", "参数B:"))
        self.groupBox_8.setTitle(_translate("Form", "所有偏压qpi"))
        self.groupBox_4.setTitle(_translate("Form", "单偏压qpi"))
        self.groupBox_3.setTitle(_translate("Form", "Bias"))
        self.label.setText(_translate("Form", "0mV"))

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_Form()
    ui.setupUi(mainWindow)
    mainWindow.show()
    app.exec_()