# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'real_space.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(772, 376)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(40, 70, 281, 271))
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(330, 70, 281, 271))
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(40, 20, 341, 51))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 20, 71, 21))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_5.setGeometry(QtCore.QRect(250, 20, 81, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_4.setGeometry(QtCore.QRect(90, 20, 71, 21))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_6.setGeometry(QtCore.QRect(170, 20, 71, 21))
        self.pushButton_6.setObjectName("pushButton_6")
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(390, 20, 261, 51))
        self.groupBox_4.setObjectName("groupBox_4")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 20, 81, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_4.setGeometry(QtCore.QRect(200, 20, 51, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setGeometry(QtCore.QRect(100, 20, 91, 21))
        self.label.setObjectName("label")
        self.groupBox_5 = QtWidgets.QGroupBox(Form)
        self.groupBox_5.setGeometry(QtCore.QRect(610, 70, 41, 271))
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalSlider = QtWidgets.QSlider(self.groupBox_5)
        self.verticalSlider.setGeometry(QtCore.QRect(10, 30, 20, 231))
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.label_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 21, 16))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setToolTip(_translate("Form", "显示的是原始的图像"))
        self.groupBox.setTitle(_translate("Form", "Real Space map"))
        self.groupBox_2.setToolTip(_translate("Form", "显示的是处理之后的图像"))
        self.groupBox_2.setTitle(_translate("Form", "Real Space processed"))
        self.groupBox_3.setTitle(_translate("Form", "OpenCV_Toolbox"))
        self.pushButton_3.setToolTip(_translate("Form", "open_cv的功能,尚未开发"))
        self.pushButton_3.setText(_translate("Form", "消除刮痕"))
        self.pushButton_5.setText(_translate("Form", "cap_vortex"))
        self.pushButton_4.setToolTip(_translate("Form", "open_cv的功能,尚未开发"))
        self.pushButton_4.setText(_translate("Form", "过滤"))
        self.pushButton_6.setToolTip(_translate("Form", "open_cv的功能,尚未开发"))
        self.pushButton_6.setText(_translate("Form", "linecut"))
        self.groupBox_4.setTitle(_translate("Form", "额外添加的fit"))
        self.pushButton_7.setToolTip(_translate("Form", "拟合出相干长度,这个功能只是额外添加的"))
        self.pushButton_7.setText(_translate("Form", "vortex_fit"))
        self.label.setText(_translate("Form", "coherent length"))
        self.groupBox_5.setTitle(_translate("Form", "Bias"))
        self.label_2.setText(_translate("Form", "0mV"))

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_Form()
    ui.setupUi(mainWindow)
    mainWindow.show()
    app.exec_()