import sys
import json
import numpy as np

from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5 import QtCore
from PyQt5 import QtGui

import matplotlib

matplotlib.use('Qt5Agg')
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.backends.backend_qt5 import NavigationToolbar2QT as NavigationToolbar
import matplotlib.pyplot as plt


class SC_GAP_Fitting_Window():

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(796, 488)
        self.widget_superconductor_STM = QWidget(Form)
        self.widget_superconductor_STM.setGeometry(QtCore.QRect(20, 10, 761, 401))
        self.widget_superconductor_STM.setObjectName("widget_superconductor_STM")
        #
        self.dat_file_list = QListWidget(self.widget_superconductor_STM)
        self.dat_file_list.setGeometry(QtCore.QRect(10, 40, 51, 351))
        self.dat_file_list.setObjectName("dat_file_list")
        #
        self.groupBox_Single_Pixel = QGroupBox(self.widget_superconductor_STM)
        self.groupBox_Single_Pixel.setGeometry(QtCore.QRect(70, 10, 441, 381))
        self.groupBox_Single_Pixel.setObjectName("groupBox_Single_Pixel")
        #
        self.groupBox_fitting_parameters = QGroupBox(self.widget_superconductor_STM)
        self.groupBox_fitting_parameters.setGeometry(QtCore.QRect(520, 120, 231, 271))
        self.groupBox_fitting_parameters.setObjectName("groupBox_fitting_parameters")
        #
        self.label_parameter_A = QLabel(self.groupBox_fitting_parameters)
        self.label_parameter_A.setGeometry(QtCore.QRect(90, 30, 41, 16))
        self.label_parameter_A.setObjectName("label_parameter_A")
        self.label_parameter_B = QLabel(self.groupBox_fitting_parameters)
        self.label_parameter_B.setGeometry(QtCore.QRect(90, 90, 41, 16))
        self.label_parameter_B.setObjectName("label_parameter_B")
        self.label_parameter_C = QLabel(self.groupBox_fitting_parameters)
        self.label_parameter_C.setGeometry(QtCore.QRect(90, 150, 41, 16))
        self.label_parameter_C.setObjectName("label_parameter_C")
        self.label_parameter_D = QLabel(self.groupBox_fitting_parameters)
        self.label_parameter_D.setGeometry(QtCore.QRect(90, 220, 41, 16))
        self.label_parameter_D.setObjectName("label_parameter_D")
        self.horizontalSlider_parameter_A = QSlider(self.groupBox_fitting_parameters)
        self.horizontalSlider_parameter_A.setGeometry(QtCore.QRect(50, 50, 131, 16))
        self.horizontalSlider_parameter_A.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_parameter_A.setObjectName("horizontalSlider_parameter_A")
        self.horizontalSlider_parameter_B = QSlider(self.groupBox_fitting_parameters)
        self.horizontalSlider_parameter_B.setGeometry(QtCore.QRect(50, 110, 131, 16))
        self.horizontalSlider_parameter_B.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_parameter_B.setObjectName("horizontalSlider_parameter_B")
        self.horizontalSlider_parameter_C = QSlider(self.groupBox_fitting_parameters)
        self.horizontalSlider_parameter_C.setGeometry(QtCore.QRect(50, 170, 131, 16))
        self.horizontalSlider_parameter_C.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_parameter_C.setObjectName("horizontalSlider_parameter_C")
        self.horizontalSlider_parameter_D = QSlider(self.groupBox_fitting_parameters)
        self.horizontalSlider_parameter_D.setGeometry(QtCore.QRect(50, 240, 131, 16))
        self.horizontalSlider_parameter_D.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_parameter_D.setObjectName("horizontalSlider_parameter_D")
        self.lineEdit_parameter_D_min = QLineEdit(self.groupBox_fitting_parameters)
        self.lineEdit_parameter_D_min.setGeometry(QtCore.QRect(10, 240, 31, 20))
        self.lineEdit_parameter_D_min.setObjectName("lineEdit_parameter_D_min")
        self.lineEdit_parameter_D_max = QLineEdit(self.groupBox_fitting_parameters)
        self.lineEdit_parameter_D_max.setGeometry(QtCore.QRect(190, 240, 31, 20))
        self.lineEdit_parameter_D_max.setObjectName("lineEdit_parameter_D_max")
        self.lineEdit_parameter_C_min = QLineEdit(self.groupBox_fitting_parameters)
        self.lineEdit_parameter_C_min.setGeometry(QtCore.QRect(10, 170, 31, 20))
        self.lineEdit_parameter_C_min.setObjectName("lineEdit_parameter_C_min")
        self.lineEdit_parameter_C_max = QLineEdit(self.groupBox_fitting_parameters)
        self.lineEdit_parameter_C_max.setGeometry(QtCore.QRect(190, 170, 31, 20))
        self.lineEdit_parameter_C_max.setObjectName("lineEdit_parameter_C_max")
        self.lineEdit_parameter_B_min = QLineEdit(self.groupBox_fitting_parameters)
        self.lineEdit_parameter_B_min.setGeometry(QtCore.QRect(10, 110, 31, 20))
        self.lineEdit_parameter_B_min.setObjectName("lineEdit_parameter_B_min")
        self.lineEdit_parameter_B_max = QLineEdit(self.groupBox_fitting_parameters)
        self.lineEdit_parameter_B_max.setGeometry(QtCore.QRect(190, 110, 31, 20))
        self.lineEdit_parameter_B_max.setObjectName("lineEdit_parameter_B_max")
        self.lineEdit_parameter_A_max = QLineEdit(self.groupBox_fitting_parameters)
        self.lineEdit_parameter_A_max.setGeometry(QtCore.QRect(190, 50, 31, 20))
        self.lineEdit_parameter_A_max.setObjectName("lineEdit_parameter_A_max")
        self.lineEdit_parameter_A_min = QLineEdit(self.groupBox_fitting_parameters)
        self.lineEdit_parameter_A_min.setGeometry(QtCore.QRect(10, 50, 31, 20))
        self.lineEdit_parameter_A_min.setObjectName("lineEdit_parameter_A_min")
        self.pushButton_move_A = QPushButton(self.groupBox_fitting_parameters)
        self.pushButton_move_A.setGeometry(QtCore.QRect(170, 20, 51, 23))
        self.pushButton_move_A.setObjectName("pushButton_move_A")
        self.pushButton_move_D = QPushButton(self.groupBox_fitting_parameters)
        self.pushButton_move_D.setGeometry(QtCore.QRect(170, 210, 51, 23))
        self.pushButton_move_D.setObjectName("pushButton_move_D")
        self.pushButton_move_C = QPushButton(self.groupBox_fitting_parameters)
        self.pushButton_move_C.setGeometry(QtCore.QRect(170, 140, 51, 23))
        self.pushButton_move_C.setObjectName("pushButton_move_C")
        self.pushButton_move_B = QPushButton(self.groupBox_fitting_parameters)
        self.pushButton_move_B.setGeometry(QtCore.QRect(170, 80, 51, 23))
        self.pushButton_move_B.setObjectName("pushButton_move_B")
        #
        self.Load_dat_file_btn = QPushButton(self.widget_superconductor_STM)
        self.Load_dat_file_btn.setGeometry(QtCore.QRect(10, 10, 51, 23))
        self.Load_dat_file_btn.setObjectName("Load_dat_file_btn")
        #
        self.groupBox_fitting = QGroupBox(self.widget_superconductor_STM)
        self.groupBox_fitting.setGeometry(QtCore.QRect(520, 10, 231, 101))
        self.groupBox_fitting.setObjectName("groupBox_fitting")
        #
        self.pushButton_fitting = QPushButton(self.groupBox_fitting)
        self.pushButton_fitting.setGeometry(QtCore.QRect(80, 70, 51, 20))
        self.pushButton_fitting.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.pushButton_fitting.setObjectName("pushButton_fitting")
        self.comboBox_isotropic = QComboBox(self.groupBox_fitting)
        self.comboBox_isotropic.setGeometry(QtCore.QRect(10, 40, 67, 22))
        self.comboBox_isotropic.setObjectName("comboBox_isotropic")
        self.comboBox_isotropic.addItem("")
        self.comboBox_isotropic.addItem("")
        self.comboBox_isotropic.addItem("")
        self.comboBox_isotropic.addItem("")
        self.checkBox_isotropic = QCheckBox(self.groupBox_fitting)
        self.checkBox_isotropic.setGeometry(QtCore.QRect(10, 10, 84, 32))
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_isotropic.sizePolicy().hasHeightForWidth())
        self.checkBox_isotropic.setSizePolicy(sizePolicy)
        self.checkBox_isotropic.setMinimumSize(QtCore.QSize(0, 32))
        self.checkBox_isotropic.setObjectName("checkBox_isotropic")
        self.checkBox_anisotropic = QCheckBox(self.groupBox_fitting)
        self.checkBox_anisotropic.setGeometry(QtCore.QRect(140, 10, 84, 32))
        self.checkBox_anisotropic.setMinimumSize(QtCore.QSize(0, 32))
        self.checkBox_anisotropic.setObjectName("checkBox_anisotropic")
        self.comboBox_anisotropic = QComboBox(self.groupBox_fitting)
        self.comboBox_anisotropic.setGeometry(QtCore.QRect(140, 40, 67, 22))
        self.comboBox_anisotropic.setObjectName("comboBox_anisotropic")
        self.comboBox_anisotropic.addItem("")
        self.comboBox_anisotropic.addItem("")
        self.comboBox_anisotropic.addItem("")
        self.comboBox_anisotropic.addItem("")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.dat_file_list.setToolTip(_translate("Form", "存放加载上来的文件名"))
        self.groupBox_Single_Pixel.setTitle(_translate("Form", "single_pixel"))
        self.groupBox_fitting_parameters.setToolTip(_translate("Form", "显示拟合参数并可以自行调节"))
        self.groupBox_fitting_parameters.setTitle(_translate("Form", "拟合参数"))
        self.label_parameter_A.setToolTip(_translate("Form", "显示参数A的拟合结果"))
        self.label_parameter_A.setText(_translate("Form", "参数A:"))
        self.label_parameter_B.setToolTip(_translate("Form", "显示参数B的拟合结果"))
        self.label_parameter_B.setText(_translate("Form", "参数B:"))
        self.label_parameter_C.setToolTip(_translate("Form", "显示参数C的拟合结果"))
        self.label_parameter_C.setText(_translate("Form", "参数C:"))
        self.label_parameter_D.setToolTip(_translate("Form", "显示参数D的拟合结果"))
        self.label_parameter_D.setText(_translate("Form", "参数D:"))
        self.lineEdit_parameter_B_min.setToolTip(_translate("Form", "可输入参数B的下限,否则用默认值"))
        self.lineEdit_parameter_B_max.setToolTip(_translate("Form", "可输入参数B的上限,否则用默认值"))
        self.lineEdit_parameter_A_max.setToolTip(_translate("Form", "可输入参数A的上限,否则用默认值"))
        self.lineEdit_parameter_A_min.setToolTip(_translate("Form", "可输入参数A的下限,否则用默认值"))
        self.pushButton_move_A.setToolTip(_translate("Form", "连续变化参数A,可在拟合之间简单尝试"))
        self.pushButton_move_A.setText(_translate("Form", "move_A"))
        self.pushButton_move_D.setToolTip(_translate("Form", "连续变化参数D,可在拟合之间简单尝试"))
        self.pushButton_move_D.setText(_translate("Form", "move_D"))
        self.pushButton_move_C.setToolTip(_translate("Form", "连续变化参数C,可在拟合之间简单尝试"))
        self.pushButton_move_C.setText(_translate("Form", "move_C"))
        self.pushButton_move_B.setToolTip(_translate("Form", "连续变化参数B,可在拟合之间简单尝试"))
        self.pushButton_move_B.setText(_translate("Form", "move_B"))
        self.Load_dat_file_btn.setToolTip(_translate("Form", "加载dat文件"))
        self.Load_dat_file_btn.setText(_translate("Form", "Load"))
        self.groupBox_fitting.setToolTip(_translate("Form", "进行超导拟合"))
        self.groupBox_fitting.setTitle(_translate("Form", "拟合"))
        self.pushButton_fitting.setToolTip(_translate("Form", "进行拟合"))
        self.pushButton_fitting.setText(_translate("Form", "拟合"))
        self.comboBox_isotropic.setToolTip(_translate("Form", "选择一种各项同性的拟合方式"))
        self.comboBox_isotropic.setItemText(0, _translate("Form", "s"))
        self.comboBox_isotropic.setItemText(1, _translate("Form", "p"))
        self.comboBox_isotropic.setItemText(2, _translate("Form", "d"))
        self.comboBox_isotropic.setItemText(3, _translate("Form", "2s"))
        self.checkBox_isotropic.setToolTip(_translate("Form", "是否进行各项同性拟合"))
        self.checkBox_isotropic.setText(_translate("Form", "isotropic"))
        self.checkBox_anisotropic.setToolTip(_translate("Form", "是否进行各项异性拟合"))
        self.checkBox_anisotropic.setText(_translate("Form", "anisotropic"))
        self.comboBox_anisotropic.setToolTip(_translate("Form", "选择一种各项异性的拟合方式"))
        self.comboBox_anisotropic.setItemText(0, _translate("Form", "s"))
        self.comboBox_anisotropic.setItemText(1, _translate("Form", "p"))
        self.comboBox_anisotropic.setItemText(2, _translate("Form", "d"))
        self.comboBox_anisotropic.setItemText(3, _translate("Form", "2s"))

if __name__ == "__main__":
    app = QApplication(sys.argv)
    mainWindow = QMainWindow()
    form = SC_GAP_Fitting_Window()
    form.setupUi(mainWindow)
    mainWindow.show()
    app.exec_()
